name: time_counter
description: A new Flutter project.
publish_to: "none"

version: 0.0.5+5

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.2
  get_it: ^7.7.0
  go_router: ^14.2.0
  injectable: ^2.4.2
  shared_preferences: ^2.2.1
  theme_manager: ^2.0.4

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
